global using Shortener.Services;
global using Shortener.Common;
global using Microsoft.AspNetCore.Mvc;
global using Shortener.IServices;
global using Shortener.WebApplicationExtensions;
global using System.Text.RegularExpressions;
global using Microsoft.EntityFrameworkCore;
global using Shortener.Middlewares;
global using Shortener.Persistence;